# Production overlay for docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  vanta-bot:
    environment:
      # Production-specific environment overrides
      - LOG_JSON=true
      - ENVIRONMENT=production
      - REQUIRE_CRITICAL_SECRETS=true
      # No fallback for DATABASE_URL in production
      - DATABASE_URL=${DATABASE_URL:?set}
      - REDIS_URL=${REDIS_URL:?set}
    # Remove host port mappings for security
    ports: []
    # Ensure non-root user is enforced
    user: "10001:10001"
    read_only: true
    tmpfs:
      - /tmp
      - /app/tmp
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  postgres:
    # Remove host port exposure in production
    ports: []
    environment:
      # Require all PostgreSQL credentials in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?set}

  redis:
    # Remove host port exposure in production
    ports: []
    # Enable Redis authentication if password provided
    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --tcp-keepalive 60
      --timeout 300
      ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}

  # Tools services should not run in production
  redis-commander:
    profiles: [never]

  pgadmin:
    profiles: [never]
