"""baseline schema 2025-09-30

Revision ID: 000000000001
Revises: 
Create Date: 2025-09-29 22:21:10.803955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import LargeBinary

# Import custom types for encrypted fields
try:
    from src.database.types import EncryptedBytes, EncryptedJSON
except ImportError:
    # Fallback to LargeBinary if types not available
    EncryptedBytes = LargeBinary
    EncryptedJSON = LargeBinary


# revision identifiers, used by Alembic.
revision = '000000000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('secret_enc', EncryptedJSON(), nullable=True),
    sa.Column('meta_enc', EncryptedJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_creds_user_provider', 'api_credentials', ['user_id', 'provider'], unique=False)
    op.create_index(op.f('ix_api_credentials_user_id'), 'api_credentials', ['user_id'], unique=False)
    op.create_table('copy_configurations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('leader_address', sa.String(length=64), nullable=False),
    sa.Column('sizing_mode', sa.String(length=32), nullable=False),
    sa.Column('sizing_value', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('max_slippage_bps', sa.BigInteger(), nullable=False),
    sa.Column('max_leverage', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('notional_cap', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('pair_filters', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_configurations_created_at'), 'copy_configurations', ['created_at'], unique=False)
    op.create_index(op.f('ix_copy_configurations_leader_address'), 'copy_configurations', ['leader_address'], unique=False)
    op.create_index(op.f('ix_copy_configurations_updated_at'), 'copy_configurations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_copy_configurations_user_id'), 'copy_configurations', ['user_id'], unique=False)
    op.create_table('copy_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('leader_address', sa.String(length=64), nullable=False),
    sa.Column('leader_tx_hash', sa.String(length=66), nullable=False),
    sa.Column('copy_tx_hash', sa.String(length=66), nullable=False),
    sa.Column('pair', sa.String(length=64), nullable=False),
    sa.Column('is_long', sa.Boolean(), nullable=False),
    sa.Column('size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('copy_ratio', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('opened_at', sa.BigInteger(), nullable=False),
    sa.Column('closed_at', sa.BigInteger(), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=38, scale=18), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_copy_positions_user_leader', 'copy_positions', ['user_id', 'leader_address'], unique=False)
    op.create_index('idx_copy_positions_user_status', 'copy_positions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_copy_positions_copy_tx_hash'), 'copy_positions', ['copy_tx_hash'], unique=False)
    op.create_index(op.f('ix_copy_positions_leader_address'), 'copy_positions', ['leader_address'], unique=False)
    op.create_index(op.f('ix_copy_positions_leader_tx_hash'), 'copy_positions', ['leader_tx_hash'], unique=False)
    op.create_index(op.f('ix_copy_positions_opened_at'), 'copy_positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_copy_positions_user_id'), 'copy_positions', ['user_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('pair', sa.String(length=64), nullable=False),
    sa.Column('is_long', sa.Boolean(), nullable=False),
    sa.Column('size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('notional_usd', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('fee', sa.Numeric(precision=38, scale=18), server_default='0', nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('maker_taker', sa.String(length=8), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.String(length=66), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fills_address_pair_ts', 'fills', ['address', 'pair', 'ts'], unique=False)
    op.create_index('idx_fills_address_ts', 'fills', ['address', 'ts'], unique=False)
    op.create_index('idx_fills_pair_ts', 'fills', ['pair', 'ts'], unique=False)
    op.create_index(op.f('ix_fills_address'), 'fills', ['address'], unique=False)
    op.create_index(op.f('ix_fills_block_number'), 'fills', ['block_number'], unique=False)
    op.create_index(op.f('ix_fills_pair'), 'fills', ['pair'], unique=False)
    op.create_index(op.f('ix_fills_ts'), 'fills', ['ts'], unique=False)
    op.create_index(op.f('ix_fills_tx_hash'), 'fills', ['tx_hash'], unique=False)
    op.create_table('indexed_fills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('is_long', sa.Boolean(), nullable=False),
    sa.Column('usd_1e6', sa.BigInteger(), nullable=False),
    sa.Column('collateral_usdc_1e6', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ifills_user_sym_block', 'indexed_fills', ['user_address', 'symbol', 'block_number'], unique=False)
    op.create_index(op.f('ix_indexed_fills_block_number'), 'indexed_fills', ['block_number'], unique=False)
    op.create_index(op.f('ix_indexed_fills_symbol'), 'indexed_fills', ['symbol'], unique=False)
    op.create_index(op.f('ix_indexed_fills_tx_hash'), 'indexed_fills', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_indexed_fills_user_address'), 'indexed_fills', ['user_address'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('liquidation_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sent_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sent_transactions_request_id'), 'sent_transactions', ['request_id'], unique=True)
    op.create_index(op.f('ix_sent_transactions_tx_hash'), 'sent_transactions', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_sent_transactions_wallet_id'), 'sent_transactions', ['wallet_id'], unique=False)
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('last_block', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trading_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('pair', sa.String(length=64), nullable=False),
    sa.Column('is_long', sa.Boolean(), nullable=False),
    sa.Column('entry_px', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('opened_at', sa.BigInteger(), nullable=False),
    sa.Column('closed_at', sa.BigInteger(), nullable=True),
    sa.Column('pnl_realized', sa.Numeric(precision=38, scale=18), server_default='0', nullable=False),
    sa.Column('fees', sa.Numeric(precision=38, scale=18), server_default='0', nullable=False),
    sa.Column('funding', sa.Numeric(precision=38, scale=18), server_default='0', nullable=False),
    sa.Column('tx_open', sa.String(length=66), nullable=False),
    sa.Column('tx_close', sa.String(length=66), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trading_positions_address_closed', 'trading_positions', ['address', 'closed_at'], unique=False)
    op.create_index('idx_trading_positions_address_opened', 'trading_positions', ['address', 'opened_at'], unique=False)
    op.create_index(op.f('ix_trading_positions_address'), 'trading_positions', ['address'], unique=False)
    op.create_index(op.f('ix_trading_positions_opened_at'), 'trading_positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_trading_positions_pair'), 'trading_positions', ['pair'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('gas_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('idx_request_payload', 'transactions', ['request_id', 'payload_hash'], unique=True)
    op.create_table('tx_intents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('intent_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tx_intents_intent_key'), 'tx_intents', ['intent_key'], unique=True)
    op.create_index('ix_txintent_status_created', 'tx_intents', ['status', 'created_at'], unique=False)
    op.create_table('tx_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('gas_used', sa.BigInteger(), nullable=False),
    sa.Column('effective_gas_price', sa.BigInteger(), nullable=False),
    sa.Column('mined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tx_receipts_tx_hash'), 'tx_receipts', ['tx_hash'], unique=True)
    op.create_table('user_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('is_long', sa.Boolean(), nullable=False),
    sa.Column('size_usd_1e6', sa.BigInteger(), nullable=False),
    sa.Column('entry_collateral_1e6', sa.BigInteger(), nullable=False),
    sa.Column('realized_pnl_1e6', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_pos_user_symbol', 'user_positions', ['user_address', 'symbol'], unique=True)
    op.create_index(op.f('ix_user_positions_symbol'), 'user_positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_user_positions_user_address'), 'user_positions', ['user_address'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('encrypted_private_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('referral_code', sa.String(length=10), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('ciphertext_privkey', sa.LargeBinary(), nullable=False),
    sa.Column('dek_wrapped', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_version', sa.String(length=16), nullable=False),
    sa.Column('kms_key_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.Column('privkey_enc', EncryptedBytes(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('tx_sends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('max_fee_per_gas', sa.BigInteger(), nullable=False),
    sa.Column('max_priority_fee_per_gas', sa.BigInteger(), nullable=False),
    sa.Column('gas_limit', sa.BigInteger(), nullable=False),
    sa.Column('raw_tx', sa.LargeBinary(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('replaced_by', sa.String(length=66), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['tx_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tx_sends_intent_id'), 'tx_sends', ['intent_id'], unique=False)
    op.create_index(op.f('ix_tx_sends_tx_hash'), 'tx_sends', ['tx_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tx_sends_tx_hash'), table_name='tx_sends')
    op.drop_index(op.f('ix_tx_sends_intent_id'), table_name='tx_sends')
    op.drop_table('tx_sends')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_positions_user_address'), table_name='user_positions')
    op.drop_index(op.f('ix_user_positions_symbol'), table_name='user_positions')
    op.drop_index('ix_user_pos_user_symbol', table_name='user_positions')
    op.drop_table('user_positions')
    op.drop_index(op.f('ix_tx_receipts_tx_hash'), table_name='tx_receipts')
    op.drop_table('tx_receipts')
    op.drop_index('ix_txintent_status_created', table_name='tx_intents')
    op.drop_index(op.f('ix_tx_intents_intent_key'), table_name='tx_intents')
    op.drop_table('tx_intents')
    op.drop_index('idx_request_payload', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_trading_positions_pair'), table_name='trading_positions')
    op.drop_index(op.f('ix_trading_positions_opened_at'), table_name='trading_positions')
    op.drop_index(op.f('ix_trading_positions_address'), table_name='trading_positions')
    op.drop_index('idx_trading_positions_address_opened', table_name='trading_positions')
    op.drop_index('idx_trading_positions_address_closed', table_name='trading_positions')
    op.drop_table('trading_positions')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_sent_transactions_wallet_id'), table_name='sent_transactions')
    op.drop_index(op.f('ix_sent_transactions_tx_hash'), table_name='sent_transactions')
    op.drop_index(op.f('ix_sent_transactions_request_id'), table_name='sent_transactions')
    op.drop_table('sent_transactions')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_index(op.f('ix_indexed_fills_user_address'), table_name='indexed_fills')
    op.drop_index(op.f('ix_indexed_fills_tx_hash'), table_name='indexed_fills')
    op.drop_index(op.f('ix_indexed_fills_symbol'), table_name='indexed_fills')
    op.drop_index(op.f('ix_indexed_fills_block_number'), table_name='indexed_fills')
    op.drop_index('ix_ifills_user_sym_block', table_name='indexed_fills')
    op.drop_table('indexed_fills')
    op.drop_index(op.f('ix_fills_tx_hash'), table_name='fills')
    op.drop_index(op.f('ix_fills_ts'), table_name='fills')
    op.drop_index(op.f('ix_fills_pair'), table_name='fills')
    op.drop_index(op.f('ix_fills_block_number'), table_name='fills')
    op.drop_index(op.f('ix_fills_address'), table_name='fills')
    op.drop_index('idx_fills_pair_ts', table_name='fills')
    op.drop_index('idx_fills_address_ts', table_name='fills')
    op.drop_index('idx_fills_address_pair_ts', table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_copy_positions_user_id'), table_name='copy_positions')
    op.drop_index(op.f('ix_copy_positions_opened_at'), table_name='copy_positions')
    op.drop_index(op.f('ix_copy_positions_leader_tx_hash'), table_name='copy_positions')
    op.drop_index(op.f('ix_copy_positions_leader_address'), table_name='copy_positions')
    op.drop_index(op.f('ix_copy_positions_copy_tx_hash'), table_name='copy_positions')
    op.drop_index('idx_copy_positions_user_status', table_name='copy_positions')
    op.drop_index('idx_copy_positions_user_leader', table_name='copy_positions')
    op.drop_table('copy_positions')
    op.drop_index(op.f('ix_copy_configurations_user_id'), table_name='copy_configurations')
    op.drop_index(op.f('ix_copy_configurations_updated_at'), table_name='copy_configurations')
    op.drop_index(op.f('ix_copy_configurations_leader_address'), table_name='copy_configurations')
    op.drop_index(op.f('ix_copy_configurations_created_at'), table_name='copy_configurations')
    op.drop_table('copy_configurations')
    op.drop_index(op.f('ix_api_credentials_user_id'), table_name='api_credentials')
    op.drop_index('idx_api_creds_user_provider', table_name='api_credentials')
    op.drop_table('api_credentials')
    # ### end Alembic commands ###
