name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push images
        run: |
          REPO=ghcr.io/${{ github.repository }}
          for svc in bot webhook worker tpsl indexer; do
            echo "Building $svc..."
            docker build -f docker/Dockerfile.$svc -t ${REPO}/${svc}:${TAG} -t ${REPO}/${svc}:latest .
            docker push ${REPO}/${svc}:${TAG}
            docker push ${REPO}/${svc}:latest
          done
